package integration

import (
	"context"
	"os"
	"testing"

	docxProvider "github.com/anasamu/microservices-library-go/filegen/providers/docx"
)

func TestDOCXProvider(t *testing.T) {
	// Create temporary directory for templates
	tmpDir := t.TempDir()

	config := &docxProvider.Config{
		TemplatePath: tmpDir,
		DefaultFont:  "Calibri",
		DefaultSize:  11,
	}

	provider, err := docxProvider.NewProvider(config)
	if err != nil {
		t.Fatalf("Failed to create DOCX provider: %v", err)
	}
	defer provider.Close()

	ctx := context.Background()

	t.Run("GenerateSimpleDocument", func(t *testing.T) {
		req := &docxProvider.FileRequest{
			Type: "docx",
			Data: map[string]interface{}{
				"title": "Test Document",
				"content": []map[string]interface{}{
					{
						"type":  "heading",
						"text":  "Introduction",
						"level": 1,
					},
					{
						"type": "paragraph",
						"text": "This is a test document generated by the DOCX provider.",
					},
					{
						"type":    "table",
						"headers": []string{"Name", "Age", "City"},
						"rows": [][]string{
							{"John Doe", "30", "New York"},
							{"Jane Smith", "25", "Los Angeles"},
						},
					},
				},
			},
		}

		response, err := provider.GenerateFile(ctx, req)
		if err != nil {
			t.Fatalf("Failed to generate DOCX file: %v", err)
		}

		if !response.Success {
			t.Fatalf("File generation failed: %s", response.Error)
		}

		if len(response.Content) == 0 {
			t.Fatal("Generated content is empty")
		}

		if response.MimeType != "application/vnd.openxmlformats-officedocument.wordprocessingml.document" {
			t.Errorf("Expected MIME type 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', got '%s'", response.MimeType)
		}
	})

	t.Run("ValidateRequest", func(t *testing.T) {
		// Test valid request
		req := &docxProvider.FileRequest{
			Type: "docx",
			Data: map[string]interface{}{"test": "data"},
		}

		if err := provider.ValidateRequest(req); err != nil {
			t.Errorf("Valid request should not fail validation: %v", err)
		}

		// Test invalid file type
		req.Type = "invalid"
		if err := provider.ValidateRequest(req); err == nil {
			t.Error("Invalid file type should fail validation")
		}

		// Test missing data
		req.Type = "docx"
		req.Data = nil
		if err := provider.ValidateRequest(req); err == nil {
			t.Error("Missing data should fail validation")
		}
	})

	t.Run("GetSupportedTypes", func(t *testing.T) {
		types := provider.GetSupportedTypes()
		if len(types) != 1 || types[0] != "docx" {
			t.Errorf("Expected supported types ['docx'], got %v", types)
		}
	})

	t.Run("GetTemplateList", func(t *testing.T) {
		templates, err := provider.GetTemplateList()
		if err != nil {
			t.Errorf("Failed to get template list: %v", err)
		}

		// Should be empty since no templates were loaded
		if len(templates) != 0 {
			t.Errorf("Expected empty template list, got %v", templates)
		}
	})
}

func TestDOCXProviderWithWriter(t *testing.T) {
	config := &docxProvider.Config{
		TemplatePath: t.TempDir(),
	}

	provider, err := docxProvider.NewProvider(config)
	if err != nil {
		t.Fatalf("Failed to create DOCX provider: %v", err)
	}
	defer provider.Close()

	ctx := context.Background()

	req := &docxProvider.FileRequest{
		Type: "docx",
		Data: map[string]interface{}{
			"title": "Test Document",
			"text":  "This is a simple test document.",
		},
	}

	// Create temporary file
	tmpFile, err := os.CreateTemp("", "test_*.docx")
	if err != nil {
		t.Fatalf("Failed to create temp file: %v", err)
	}
	defer os.Remove(tmpFile.Name())
	defer tmpFile.Close()

	// Generate file to writer
	err = provider.GenerateFileToWriter(ctx, req, tmpFile)
	if err != nil {
		t.Fatalf("Failed to generate file to writer: %v", err)
	}

	// Check if file was written
	info, err := tmpFile.Stat()
	if err != nil {
		t.Fatalf("Failed to get file info: %v", err)
	}

	if info.Size() == 0 {
		t.Fatal("Generated file is empty")
	}
}
