# AI Microservices Configuration
providers:
  openai:
    name: "openai"
    api_key: "${OPENAI_API_KEY}"
    base_url: "https://api.openai.com/v1"
    timeout: "30s"
    max_retries: 3
    default_model: "gpt-4"
    models:
      - "gpt-4"
      - "gpt-4-turbo"
      - "gpt-3.5-turbo"
    headers:
      User-Agent: "AI-Microservice/1.0"

  anthropic:
    name: "anthropic"
    api_key: "${ANTHROPIC_API_KEY}"
    base_url: "https://api.anthropic.com/v1"
    timeout: "30s"
    max_retries: 3
    default_model: "claude-3-sonnet-20240229"
    models:
      - "claude-3-opus-20240229"
      - "claude-3-sonnet-20240229"
      - "claude-3-haiku-20240307"

  google:
    name: "google"
    api_key: "${GOOGLE_API_KEY}"
    base_url: "https://generativelanguage.googleapis.com/v1beta"
    timeout: "30s"
    max_retries: 3
    default_model: "gemini-pro"
    models:
      - "gemini-pro"
      - "gemini-pro-vision"

  deepseek:
    name: "deepseek"
    api_key: "${DEEPSEEK_API_KEY}"
    base_url: "https://api.deepseek.com/v1"
    timeout: "30s"
    max_retries: 3
    default_model: "deepseek-chat"
    models:
      - "deepseek-chat"
      - "deepseek-coder"

  xai:
    name: "xai"
    api_key: "${XAI_API_KEY}"
    base_url: "https://api.x.ai/v1"
    timeout: "30s"
    max_retries: 3
    default_model: "grok-beta"
    models:
      - "grok-beta"

# Default settings
defaults:
  temperature: 0.7
  max_tokens: 1000
  timeout: "30s"
  fallback_enabled: true
  primary_provider: "openai"

# Health check settings
health_check:
  interval: "60s"
  timeout: "10s"
  enabled: true

# Statistics settings
statistics:
  enabled: true
  retention_days: 30
